PurpleBuzzPr/PurpleBuzzPr/Models/Work.cs
using PurpleBuzzPr.Models.Base;
using System.ComponentModel.DataAnnotations;
using System.Diagnostics.CodeAnalysis;

namespace PurpleBuzzPr.Models
{
    public class Work : BaseAuditableEntity
    {
        
        public int Id { get; set; }
        [MinLength(3), DisallowNull]
        public string Title { get; set; }
        public string Description { get; set; }
        [AllowNull]
        public string MainImageUrl { get; set; }
        public int ServiceId { get; set; }
        public Service? Service { get; set; }

    }
}

PurpleBuzzPr/PurpleBuzzPr/Areas/Admin/Controllers/WorkController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PurpleBuzzPr.DAL;
using PurpleBuzzPr.Models;

namespace PurpleBuzzPr.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class WorkController : Controller
    {
        private readonly AppDbContext _context;
        public WorkController(AppDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
           IEnumerable<Work> works =await _context.Works.ToListAsync();
            return View(works);
        }

      
        public IActionResult Delete(int Id)
        {
            Work? deletedWork = _context.Works.Find(Id);
            if (deletedWork != null)
            {
                return NotFound();  
            }
            else
            {
                _context.Works.Remove(deletedWork);
                _context.SaveChanges();
            }
            return RedirectToAction(nameof(Index));
        }


        public IActionResult Create() 
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Work work)
        {

            if (!ModelState.IsValid)
            {
                return BadRequest("Something went wrong");
            }

                _context.Works.Add(work);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
        }

        public IActionResult Update(int? Id)
        {
            Work? work = _context.Works.Find(Id);
            if(work is  null)
            {
                return NotFound("No such work");
            }
            return View(work);  
        }

        [HttpPost]
        public IActionResult Update(Work work)
        {
            Work? updatedWork = _context.Works.AsNoTracking().FirstOrDefault(x => x.Id == work.Id);
            if (updatedWork is null)
            {
                return NotFound("No such work");
            }
       
            _context.Works.Update(work);
            _context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }

    }
}

PurpleBuzzPr/PurpleBuzzPr/Areas/Admin/Controllers/WorksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PurpleBuzzPr.DAL;
using PurpleBuzzPr.Models;

namespace PurpleBuzzPr.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class WorksController : Controller
    {
        private readonly AppDbContext _context;

        public WorksController(AppDbContext context)
        {
            _context = context;
        }

  
        public async Task<IActionResult> Index()
        {
            var appDbContext = _context.Works.Include(w => w.Service);
            return View(await appDbContext.ToListAsync());
        }



        public IActionResult Create()
        {
            ViewBag.Services = _context.Services;
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Work work)
        {
            if (ModelState.IsValid)
            {
                _context.Works.Add(work);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
          
            return View(work);
        }
    }
}

PurpleBuzzPr/PurpleBuzzPr/Controllers/SingleWorkController.cs
using Microsoft.AspNetCore.Mvc;

namespace PurpleBuzzPr.Controllers;

public class SingleWorkController : Controller
{
    public IActionResult Index(int id)
    {
        return View();
    }
}

PurpleBuzzPr/PurpleBuzzPr/Controllers/WorkController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PurpleBuzzPr.DAL;
using PurpleBuzzPr.Models;

namespace PurpleBuzzPr.Controllers;

public class WorkController : Controller
{
    private readonly AppDbContext _context;
    public WorkController(AppDbContext context)
    {
        _context = context;
    }
    public async Task<IActionResult> Index()
    {
        IEnumerable<Work> works = await _context.Works.ToListAsync();

        return View(works);
    }
 

  
    public IActionResult SingleWork(int id)
    {
        return View();
    }
  
}

PurpleBuzzPr/PurpleBuzzPr/Views/Work/Index.cshtml
<!-- Start Banner Hero -->
<div id="work_banner" class="banner-wrapper bg-light w-100 py-5">
    <div class="banner-vertical-center-work container text-light d-flex justify-content-center align-items-center py-5 p-0">
        <div class="banner-content col-lg-8 col-12 m-lg-auto text-center">
            <h1 class="banner-heading h2 display-3 pb-5 semi-bold-600 typo-space-line-center">Our Work</h1>
            <h3 class="h4 pb-2 regular-400">Elit, sed do eiusmod tempor incididunt</h3>
            <p class="banner-body pb-2 light-300">
                Vector illustration <a class="text-white" href="http://freepik.com/" target="_blank">Freepik</a>.
                Lorem ipsum dolor sit amet, consectetur adipiscing elit,
                sed do eiusmod tempor incididunt ut labore et dolore magna
                aliqua. Quis ipsum suspendisse ultrices gravida. Risus
                commodo viverra maecenas accumsan lacus.
            </p>
            <button type="submit" class="btn rounded-pill btn-outline-light px-4 me-4 light-300">Learn More</button>
            <button type="submit" class="btn rounded-pill btn-secondary text-light px-4 light-300">Contact Us</button>
        </div>
    </div>
</div>
<!-- End Banner Hero -->
<!-- Start Our Work -->
<section class="container py-5">
    <div class="row justify-content-center my-5">
        <div class="filter-btns shadow-md rounded-pill text-center col-auto">
            <a class="filter-btn btn rounded-pill btn-outline-primary border-0 m-md-2 px-md-4 active" data-filter=".project" href="#">All</a>
            <a class="filter-btn btn rounded-pill btn-outline-primary border-0 m-md-2 px-md-4" data-filter=".business" href="#">Business</a>
            <a class="filter-btn btn rounded-pill btn-outline-primary border-0 m-md-2 px-md-4" data-filter=".marketing" href="#">Marketing</a>
            <a class="filter-btn btn rounded-pill btn-outline-primary border-0 m-md-2 px-md-4" data-filter=".social" href="#">Social Media</a>
            <a class="filter-btn btn rounded-pill btn-outline-primary border-0 m-md-2 px-md-4" data-filter=".graphic" href="#">Graphic</a>
        </div>
    </div>

    <div class="row projects gx-lg-5">
        <a asp-controller="SingleWork" asp-action="Index" class="col-sm-6 col-lg-4 text-decoration-none project marketing social business">
            <div class="service-work overflow-hidden card mb-5 mx-5 m-sm-0">
                <img class="card-img-top" src="~/img/our-work-01.jpg" alt="...">
                <div class="card-body">
                    <h5 class="card-title light-300 text-dark">Digital Marketing</h5>
                    <p class="card-text light-300 text-dark">
                        Lorem ipsum dolor sit amet, consectetur adipisicing elit,
                        sed do eiusmod tempor incididunt ut labore et dolor.
                    </p>
                    <span class="text-decoration-none text-primary light-300">
                        Read more <i class='bx bxs-hand-right ms-1'></i>
                    </span>
                </div>
            </div>
        </a>
        <a asp-controller="SingleWork" asp-action="Index" class="col-sm-6 col-lg-4 text-decoration-none project graphic social">
            <div class="service-work overflow-hidden card mx-5 mx-sm-0 mb-5">
                <img class="card-img-top" src="~/img/our-work-02.jpg" alt="...">
                <div class="card-body">
                    <h5 class="card-title light-300 text-dark">Corporate Branding</h5>
                    <p class="card-text light-300 text-dark">
                        Ut enim ad minim veniam, quis nostrud exercitation ullamco
                        laboris nisi ut aliquip ex ea commodo consequat.
                    </p>
                    <span class="text-decoration-none text-primary light-300">
                        Read more <i class='bx bxs-hand-right ms-1'></i>
                    </span>
                </div>
            </div>
        </a>
        <a asp-controller="SingleWork" asp-action="Index" class="col-sm-6 col-lg-4 text-decoration-none project marketing graphic business">
            <div class="service-work overflow-hidden card mx-5 mx-sm-0 mb-5">
                <img class="card-img-top" src="~/img/our-work-03.jpg" alt="...">
                <div class="card-body">
                    <h5 class="card-title light-300 text-dark">Leading Digital Solution</h5>
                    <p class="card-text light-300 text-dark">
                        Duis aute irure dolor in reprehenderit in voluptate velit
                        esse cillum dolore eu fugiatdolore eu fugiat nulla pariatur.
                    </p>
                    <span class="text-decoration-none text-primary light-300">
                        Read more <i class='bx bxs-hand-right ms-1'></i>
                    </span>
                </div>
            </div>
        </a>
        <a asp-controller="SingleWork" asp-action="Index" class="col-sm-6 col-lg-4 text-decoration-none project social business">
            <div class="service-work overflow-hidden card mx-5 mx-sm-0 mb-5">
                <img class="card-img-top" src="~/img/our-work-04.jpg" alt="...">
                <div class="card-body">
                    <h5 class="card-title light-300 text-dark">Smart Applications</h5>
                    <p class="card-text light-300 text-dark">
                        Excepteur sint occaecat cupidatat non proident, sunt in
                        culpa qui officia deserunt mollit anim id est laborum.
                    </p>
                    <span class="text-decoration-none text-primary light-300">
                        Read more <i class='bx bxs-hand-right ms-1'></i>
                    </span>
                </div>
            </div>
        </a>
        <a asp-controller="SingleWork" asp-action="Index" class="col-sm-6 col-lg-4 text-decoration-none project marketing">
            <div class="service-work overflow-hidden card mx-5 mx-sm-0 mb-5">
                <img class="card-img-top" src="~/img/our-work-05.jpg" alt="...">
                <div class="card-body">
                    <h5 class="card-title light-300 text-dark">Corporate Stationary</h5>
                    <p class="card-text light-300 text-dark">
                        Excepteur sint occaecat cupidatat non proident,
                        sunt in culpa qui officia deserunt mollit anim id est laborum.
                    </p>
                    <span class="text-decoration-none text-primary light-300">
                        Read more <i class='bx bxs-hand-right ms-1'></i>
                    </span>
                </div>
            </div>
        </a>
        <a asp-controller="SingleWork" asp-action="Index" class="col-sm-6 col-lg-4 text-decoration-none project marketing graphic">
            <div class="service-work overflow-hidden card mx-5 mx-sm-0 mb-5">
                <img class="card-img-top" src="~/img/our-work-06.jpg" alt="...">
                <div class="card-body">
                    <h5 class="card-title light-300 text-dark">8 Financial Tips</h5>
                    <p class="card-text light-300 text-dark">
                        Ut enim ad minim veniam, quis nostrud exercitation ullamco
                        laboris nisi ut aliquip ex ea commodo consequat.
                    </p>
                    <span class="text-decoration-none text-primary light-300">
                        Read more <i class='bx bxs-hand-right ms-1'></i>
                    </span>
                </div>
            </div>
        </a>
    </div>
    <div class="row">
        <div class="btn-toolbar justify-content-center pb-4" role="toolbar" aria-label="Toolbar with button groups">
            <div class="btn-group me-2" role="group" aria-label="First group">
                <button type="button" class="btn btn-secondary text-white">Previous</button>
            </div>
            <div class="btn-group me-2" role="group" aria-label="Second group">
                <button type="button" class="btn btn-light">1</button>
            </div>
            <div class="btn-group me-2" role="group" aria-label="Second group">
                <button type="button" class="btn btn-secondary text-white">2</button>
            </div>
            <div class="btn-group" role="group" aria-label="Third group">
                <button type="button" class="btn btn-secondary text-white">Next</button>
            </div>
        </div>
    </div>
</section>
<!-- End Our Work -->
<!-- Start Feature Work -->
<section class="bg-light py-5">
    <div class="feature-work container my-4">
        <div class="row d-flex d-flex align-items-center">
            <div class="col-lg-5">
                <h3 class="feature-work-title h4 text-muted light-300">Featured Work</h3>
                <h1 class="feature-work-heading h2 py-3 semi-bold-600">Transform with us</h1>
                <p class="feature-work-body text-muted light-300">
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod
                    tempor incididunt ut labore et dolore magna aliqua. Quis ipsum suspendisse
                    ultrices gravida. Risus commodo viverra maecenas accumsan lacus vel facilisis.
                </p>
                <p class="feature-work-footer text-muted light-300">
                    Consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quis ipsum suspendisse ultrices gravida. Risus commodo viverra maecenas. Duis aute irure dolor in reprehenderit in voluptate velit esse
                    cillum dolore eu fugiat nulla pariatur.
                </p>
            </div>
            <div class="col-lg-6 offset-lg-1 align-left">
                <div class="row">
                    <a class="col" data-type="image" data-fslightbox="gallery" href="~/img/feature-work-1-large.jpg">
                        <img class="img-fluid" src="~/img/feature-work-1.jpg">
                    </a>
                    <a class="col" data-type="image" data-fslightbox="gallery" href="~/img/feature-work-2-large.jpg">
                        <img class="img-fluid" src="~/img/feature-work-2.jpg">
                    </a>
                </div>
                <div class="row pt-4">
                    <a class="col" data-type="image" data-fslightbox="gallery" href="~/img/feature-work-3-large.jpg">
                        <img class="img-fluid" src="~/img/feature-work-3.jpg">
                    </a>
                    <a class="col" data-type="image" data-fslightbox="gallery" href="~/img/feature-work-4-large.jpg">
                        <img class="img-fluid" src="~/img/feature-work-4.jpg">
                    </a>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- End Feature Work -->
<script src="~/js/fslightbox.js" defer></script>
<script defer>
    fsLightboxInstances['gallery'].props.loadOnlyCurrentSource = true;
</script>